openapi: 3.1.0
info:
  title: java-edu
  description: java-edu
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /users:
    post:
      summary: User register
      description: Register a new user in platform
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                datebirth:
                  type: string
                  format: date
      responses:
        "201":
          description: User created successfully
        "400":
          description: Invalid data
    get:
      summary: Get all users
      description: Get all existing users in database
      responses:
        200:
          description: Ok
  /users/{id}:
    delete:
      summary: Delete a user
      description: Delete a existing user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: User deleted successfully
        404:
          description: User not found
    get:
      summary: Get an users
      description: Get an existing user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Ok
        404:
          description: User not found
    patch:
      summary: Update an user
      description: Update an existing user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  nullable: true
                email:
                  type: string
                  format: email
                  nullable: true
                password:
                  type: string
                  format: password
                  nullable: true
                datebirth:
                  type: string
                  format: date
                  nullable: true
      responses:
        "200":
          description: User updated successfully
        "400":
          description: Invalid data

  /program:
    post:
      summary: Program register
      description: Register a new program in platform
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tittle:
                  type: string
                description:
                  type: string
                code:
                  type: string
                userId:
                  type: long
      responses:
        "201":
          description: Program created succesfully
        "400":
          description: Ivalid data
        "401":
          description: You don't have acces to this resource
        "500":
          description: Internal server error

  /program/{id}:
    put:
      summary: Update a program
      description: Update an existing program belonging to the requesting user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                programId:
                  type: long
                tittle:
                  type: string
                description:
                  type: string
                code:
                  type: string
                userId:
                  type: long
      responses:
        "200":
          description: Program updated sucessfully
        "400":
          description: Invalid data
        "401":
          description: You don't have acces to this resource
        "403":
          description: You don't have permission to update the resource
        "404":
          description: Resource not found
        "500":
          description: Internal server error
