global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'quarkus'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'blackbox'
    metrics_path: '/probe'
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://host.docker.internal:8080/q/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
